import type { Metadata } from 'next'
import localFont from 'next/font/local'
import ThemeWrapper from '@/components/theme-wrapper'
import { ViewModeProvider } from '@/contexts/viewmode-context'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Knowledge Grapht',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ViewModeProvider>
          <ThemeWrapper>{children}</ThemeWrapper>
        </ViewModeProvider>
      </body>
    </html>
  )
}
